<a href="https://colab.research.google.com/github/rishikesh1410/Projects/blob/master/RecommenderSystemPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [0]:
from __future__ import print_function, division

# Torch Libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Libraries
import numpy as np
import time
import os
import copy
import cv2
import pandas as pd
import matplotlib.pyplot as plt
from numpy import *
from scipy import optimize
np.random.seed(1)

In [0]:
os.chdir("/gdrive/My Drive/data/movielens")

In [0]:
genome_scores = pd.read_csv('genome_scores.csv')
link = pd.read_csv('link.csv')
tag = pd.read_csv('tag.csv')
genome_tags = pd.read_csv('genome_tags.csv')
movie = pd.read_csv('movie.csv')
rating = pd.read_csv('rating.csv')

In [0]:
def tabular_preview(ratings, n=15):
  
    user_groups = ratings.groupby('userId')['rating'].count()
    top_users = user_groups.sort_values(ascending=False)[:1000]

    movie_groups = ratings.groupby('movieId')['rating'].count()
    top_movies = movie_groups.sort_values(ascending=False)[:1700]

    top = (
        ratings.
        join(top_movies, rsuffix='_r', how='inner', on='movieId').
        join(top_users, rsuffix='_r', how='inner', on='userId'))

    return pd.crosstab(top.movieId, top.userId, top.rating, aggfunc=np.sum)

In [0]:
frame = tabular_preview(rating)

In [0]:
train_data = np.array(frame)

In [0]:
did_rate = np.ndarray(shape = (1700,1000))

In [0]:
for i in range(1700):
  for j in range(1000):
    if np.isnan(train_data[i][j]):
      train_data[i][j]=0

In [0]:
did_rate = (train_data != 0 )* 1

In [11]:
train_data

array([[5. , 4. , 5. , ..., 5. , 3. , 5. ],
       [5. , 0. , 0. , ..., 3. , 2. , 3. ],
       [2. , 0. , 0. , ..., 4. , 2. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 4.5],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 3. , 0. , ..., 0. , 0. , 0. ]])

In [12]:
did_rate

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [0]:
def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]

    ratings_mean = np.zeros(shape = (num_movies, 1))
    ratings_norm = np.zeros(shape = ratings.shape)

    for i in range(num_movies): 
        idx = np.where(did_rate[i] == True)[0]
        ratings_mean[i] = np.mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]

    return ratings_norm, ratings_mean

In [0]:
rating, rating_mean = normalize_ratings(train_data, did_rate)

In [0]:
num_users = 1000
num_movies = 1700
num_features = 3

In [0]:
movie_features = random.randn(num_movies, num_features)
user_prefs = random.randn(num_users, num_features)

In [23]:
movie_features = torch.tensor(movie_features, requires_grad=True)
user_prefs = torch.tensor(user_prefs, requires_grad=True)
did_rate = torch.tensor(did_rate, dtype=torch.double, requires_grad=False)
rating = torch.tensor(rating, requires_grad=False)
rating_mean = torch.tensor(rating_mean, dtype=torch.double, requires_grad=False)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """


In [0]:
def loss(movie_features, user_prefs, ratings, did_rate):

  cost = torch.sum( ((torch.mm(movie_features, torch.t(user_prefs)) * did_rate) - ratings) ** 2 ) / (1700*1000)
  return cost

In [0]:
optimizer = optim.Adam([movie_features, user_prefs], lr=0.001)

In [0]:
def train(epoch):
  minimum_loss = 100
  epoch_min_loss = 0
  for i in range(epoch):
    train_loss = loss(movie_features, user_prefs, rating, did_rate)
    train_loss.backward()
    optimizer.step()
    if train_loss <= minimum_loss:
      minimum_loss = train_loss
      X = movie_features
      theta = user_prefs
      epoch_min_loss = epoch  
    print('Epoch : {} ----- Train Loss : {} ------- Minimum Loss {}' .format(i, train_loss, minimum_loss))

In [27]:
train(1000)

Epoch : 0 ----- Train Loss : 1.990342858157188 ------- Minimum Loss 1.990342858157188
Epoch : 1 ----- Train Loss : 1.985337206954278 ------- Minimum Loss 1.985337206954278
Epoch : 2 ----- Train Loss : 1.9805172691342667 ------- Minimum Loss 1.9805172691342667
Epoch : 3 ----- Train Loss : 1.9757454268056918 ------- Minimum Loss 1.9757454268056918
Epoch : 4 ----- Train Loss : 1.970974167978855 ------- Minimum Loss 1.970974167978855
Epoch : 5 ----- Train Loss : 1.9661818904471102 ------- Minimum Loss 1.9661818904471102
Epoch : 6 ----- Train Loss : 1.9613572871914797 ------- Minimum Loss 1.9613572871914797
Epoch : 7 ----- Train Loss : 1.956493981502662 ------- Minimum Loss 1.956493981502662
Epoch : 8 ----- Train Loss : 1.951588273793094 ------- Minimum Loss 1.951588273793094
Epoch : 9 ----- Train Loss : 1.9466380558559184 ------- Minimum Loss 1.9466380558559184
Epoch : 10 ----- Train Loss : 1.9416422307893613 ------- Minimum Loss 1.9416422307893613
Epoch : 11 ----- Train Loss : 1.936600382

In [28]:
print(user_prefs)

tensor([[ 0.3034, -0.7378, -0.1330],
        [ 0.2981, -0.4893, -0.6389],
        [-0.5103,  0.0422, -0.5147],
        ...,
        [ 0.4630, -0.0205, -0.1432],
        [-0.3668, -0.0026,  0.2953],
        [ 0.0584, -0.4979, -0.3386]], dtype=torch.float64, requires_grad=True)


In [29]:
print(movie_features)

tensor([[-0.5957, -0.2301,  0.1568],
        [-0.6648,  0.3481, -0.5716],
        [-0.4021,  0.3735, -0.3362],
        ...,
        [-0.4084,  0.0929, -0.2248],
        [ 0.0551, -0.1700,  0.2585],
        [ 0.5950,  0.3690, -0.5245]], dtype=torch.float64, requires_grad=True)


In [0]:
predictions = torch.mm(movie_features, torch.t(user_prefs))

In [0]:
predictions = predictions + rating_mean

In [32]:
print(predictions)

tensor([[3.9366, 3.8032, 4.1820,  ..., 3.6749, 4.2338, 3.9951],
        [2.5314, 2.9105, 3.5620,  ..., 2.6808, 2.9880, 2.8953],
        [2.3879, 2.6529, 3.1347,  ..., 2.5950, 2.7878, 2.6451],
        ...,
        [3.4828, 3.6217, 3.9734,  ..., 3.4866, 3.7285, 3.6514],
        [3.7120, 3.5387, 3.4359,  ..., 3.5962, 3.6608, 3.6046],
        [3.8550, 4.2090, 3.8590,  ..., 4.2201, 3.5029, 3.9056]],
       dtype=torch.float64, grad_fn=<AddBackward0>)


In [33]:
all_predictions = torch.tensor(predictions+0.5 , dtype=torch.long)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [34]:
print(all_predictions)

tensor([[4, 4, 4,  ..., 4, 4, 4],
        [3, 3, 4,  ..., 3, 3, 3],
        [2, 3, 3,  ..., 3, 3, 3],
        ...,
        [3, 4, 4,  ..., 3, 4, 4],
        [4, 4, 3,  ..., 4, 4, 4],
        [4, 4, 4,  ..., 4, 4, 4]])


In [35]:
print(train_data)

[[5.  4.  5.  ... 5.  3.  5. ]
 [5.  0.  0.  ... 3.  2.  3. ]
 [2.  0.  0.  ... 4.  2.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.  4.5]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  3.  0.  ... 0.  0.  0. ]]


In [36]:
loss(movie_features, user_prefs, rating, did_rate)

tensor(0.4758, dtype=torch.float64, grad_fn=<DivBackward0>)

In [0]:
pd.DataFrame(movie_features.detach().numpy()).to_csv('new_movie_features.csv')

In [0]:
pd.DataFrame(user_prefs.detach().numpy()).to_csv('new_user_prefs.csv')

In [0]:
!ls

genome_scores.csv  movie_features.csv	      rating.csv
genome_tags.csv    movielens-20m-dataset.zip  rating_with_name.csv
link.csv	   new_movie_features.csv     tag.csv
movie.csv	   new_user_prefs.csv	      user_prefs.csv


In [0]:
user1_preds = all_predictions[:,0]

In [0]:
user1_preds

tensor([4, 3, 3,  ..., 4, 4, 4])

In [0]:
user1_did_rate = did_rate[:,0]

In [0]:
user1_did_rate

tensor([1., 1., 1.,  ..., 0., 0., 0.], dtype=torch.float64)

In [0]:
frame.head()

userId   156     208     359     572     586     741     768     775     \
movieId                                                                   
1           5.0     4.0     5.0     5.0     2.5     5.0     NaN     4.5   
2           5.0     NaN     NaN     3.5     3.0     3.0     3.0     2.0   
3           2.0     NaN     NaN     3.5     2.0     3.0     NaN     3.5   
4           3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           3.0     NaN     NaN     3.5     3.0     4.0     2.0     1.0   

userId   903     982      ...    136875  136989  137037  137202  137277  \
movieId                   ...                                             
1           4.0     3.0   ...       4.0     2.0     4.0     4.5     4.0   
2           4.0     2.0   ...       3.0     2.0     3.0     2.5     2.5   
3           2.0     2.0   ...       NaN     NaN     2.0     3.5     3.0   
4           2.0     2.0   ...       NaN     NaN     NaN     NaN     NaN   
5           3.0     2.5   ...       NaN     4.5     3.0     NaN     3.0   

userId   137343  137686  137885  138208  138325  
movieId                                          
1           4.0     5.0     5.0     3.0     5.0  
2           2.5     3.0     3.0     2.0     3.0  
3           3.5     3.0     4.0     2.0     NaN  
4           NaN     NaN     2.0     2.0     NaN  
5           3.5     NaN     3.0     2.0     NaN  

[5 rows x 1000 columns]

In [0]:
all_predictions_arr = all_predictions.numpy()

In [0]:
all_predictions_arr

array([[4, 4, 4, ..., 4, 3, 4],
       [3, 3, 3, ..., 3, 3, 3],
       [3, 3, 3, ..., 2, 2, 3],
       ...,
       [4, 4, 4, ..., 4, 3, 4],
       [4, 4, 4, ..., 4, 3, 4],
       [4, 4, 4, ..., 4, 4, 4]])

In [0]:
result_frame = pd.DataFrame(all_predictions_arr, index=frame.index, columns = frame.columns)

In [0]:
result_frame

userId   156     208     359     572     586     741     768     775     \
movieId                                                                   
1             4       4       4       4       4       5       4       4   
2             3       3       3       3       3       3       3       2   
3             3       3       3       3       3       3       3       3   
4             3       3       3       2       3       3       3       2   
5             3       3       3       3       3       4       3       2   
6             4       4       4       4       4       4       4       4   
7             4       3       3       3       3       4       3       3   
9             2       2       2       3       2       3       2       3   
10            3       3       4       3       3       4       3       3   
11            4       4       4       4       4       4       4       3   
12            2       2       2       2       2       3       2       2   
14            4       4       3       4       4       3       4       3   
15            3       3       2       3       2       3       3       2   
16            4       4       4       4       4       4       4       4   
17            5       4       4       4       4       4       4       4   
18            4       3       3       4       3       4       4       3   
19            3       2       3       2       2       3       2       2   
20            3       3       2       3       2       3       3       3   
21            4       4       4       3       4       4       4       3   
22            3       3       4       3       3       4       3       3   
23            3       3       3       3       3       3       3       3   
24            3       3       3       3       3       4       3       3   
25            4       4       3       4       3       4       4       4   
26            3       3       3       3       3       3       3       3   
28            4       4       4       4       4       4       4       4   
29            3       4       4       3       4       4       3       4   
31            3       3       3       3       3       3       3       3   
32            5       4       4       4       4       4       4       4   
34            4       4       4       4       4       4       4       4   
36            4       4       4       4       4       4       4       3   
...         ...     ...     ...     ...     ...     ...     ...     ...   
72011         4       4       4       4       4       4       4       4   
72226         5       4       4       4       4       4       4       4   
72998         4       4       4       4       4       4       4       4   
73017         4       4       4       4       4       4       4       3   
74458         4       4       4       4       4       4       4       3   
74789         3       3       3       3       3       3       3       3   
76093         4       4       4       4       4       4       4       4   
76251         4       4       4       4       3       4       4       4   
77561         4       3       3       3       3       4       3       3   
78499         5       4       4       4       4       5       4       4   
79091         4       4       4       4       4       4       4       3   
79132         4       4       4       4       4       4       4       4   
79702         5       4       4       4       4       4       4       4   
80463         5       4       4       4       4       5       4       4   
81591         4       4       4       4       4       4       4       4   
81834         4       4       4       4       4       4       4       3   
81845         4       4       3       5       4       4       4       5   
82459         4       4       4       4       4       4       4       4   
85414         3       4       3       4       3       3       3       4   
87232         4       4       4       4       4       4       4       4   
88125         4       4  

In [0]:
frame

userId   156     208     359     572     586     741     768     775     \
movieId                                                                   
1           5.0     4.0     5.0     5.0     2.5     5.0     NaN     4.5   
2           5.0     NaN     NaN     3.5     3.0     3.0     3.0     2.0   
3           2.0     NaN     NaN     3.5     2.0     3.0     NaN     3.5   
4           3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           3.0     NaN     NaN     3.5     3.0     4.0     2.0     1.0   
6           4.0     NaN     5.0     NaN     4.5     3.5     4.0     3.5   
7           4.0     NaN     NaN     NaN     NaN     4.5     NaN     3.0   
9           3.0     NaN     NaN     NaN     NaN     NaN     3.0     NaN   
10          4.0     NaN     4.0     NaN     4.0     4.0     4.0     4.5   
11          5.0     3.0     4.0     3.5     2.5     NaN     NaN     4.0   
12          3.0     NaN     NaN     NaN     NaN     0.5     3.0     1.5   
14          NaN     4.0     NaN     NaN     NaN     4.5     NaN     4.0   
15          4.0     NaN     NaN     NaN     NaN     0.5     3.0     1.0   
16          4.0     1.5     NaN     4.0     4.5     4.0     3.0     4.0   
17          4.0     5.0     NaN     NaN     NaN     4.5     NaN     4.0   
18          3.0     NaN     NaN     NaN     3.5     NaN     NaN     3.5   
19          NaN     NaN     3.0     2.5     3.0     0.5     NaN     1.5   
20          3.0     NaN     NaN     NaN     3.0     NaN     NaN     NaN   
21          4.0     4.5     NaN     4.0     NaN     3.5     3.0     2.5   
22          4.0     NaN     4.0     NaN     NaN     2.5     4.0     3.0   
23          3.0     NaN     NaN     NaN     3.5     NaN     3.0     NaN   
24          4.0     NaN     3.5     3.0     NaN     NaN     NaN     2.5   
25          4.0     2.0     NaN     NaN     3.5     4.5     NaN     4.0   
26          NaN     NaN     NaN     NaN     NaN     5.0     NaN     3.5   
28          NaN     4.0     NaN     NaN     NaN     NaN     NaN     1.0   
29          NaN     5.0     2.0     NaN     NaN     NaN     NaN     4.0   
31          NaN     NaN     NaN     4.0     NaN     5.0     NaN     2.0   
32          5.0     3.0     3.0     4.5     4.0     5.0     5.0     4.0   
34          3.0     4.5     4.0     3.5     2.5     1.0     NaN     4.0   
36          3.5     5.0     3.0     4.0     NaN     NaN     NaN     3.5   
...         ...     ...     ...     ...     ...     ...     ...     ...   
72011       NaN     4.0     NaN     NaN     4.5     NaN     NaN     NaN   
72226       NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
72998       NaN     2.5     4.5     NaN     5.0     NaN     3.0     NaN   
73017       NaN     NaN     NaN     4.0     3.5     NaN     3.5     NaN   
74458       NaN     3.0     NaN     5.0     4.5     NaN     3.0     NaN   
74789       NaN     NaN     NaN     NaN     NaN     NaN     3.5     NaN   
76093       NaN     NaN     NaN     NaN     4.0     NaN     3.5     NaN   
76251       NaN     NaN     NaN     NaN     5.0     NaN     3.5     NaN   
77561       NaN     NaN     NaN     4.0     4.5     NaN     3.5     NaN   
78499       NaN     4.5     NaN     4.5     4.0     NaN     NaN     NaN   
79091       NaN     NaN     NaN     NaN     4.5     NaN     NaN     NaN   
79132       NaN     NaN     4.5     4.0     5.0     NaN     4.0     NaN   
79702       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
80463       NaN     4.0     NaN     NaN     NaN     NaN     NaN     NaN   
81591       NaN     3.0     4.0     4.0     NaN     NaN     4.0     NaN   
81834       NaN     NaN     NaN     NaN     NaN     NaN     3.5     NaN   
81845       NaN     4.5     NaN     3.5     NaN     NaN     NaN     NaN   
82459       NaN     3.5     NaN     3.5     4.5     NaN     NaN     NaN   
85414       NaN     3.5     NaN     4.5     3.5     NaN     NaN     NaN   
87232       NaN     NaN     NaN     4.0     4.0     NaN     3.5     NaN   
88125       NaN     NaN  

In [0]:
rr = pd.read_csv('rating.csv')
mm = pd.read_csv('movie.csv')

In [0]:
lt=[]
pp = result_frame.copy()
pp['name']="kjhwkjhe"
pp.head()

userId   156  208  359  572  586  741  768  775  903  982    ...     136989  \
movieId                                                      ...              
1          4    4    4    4    4    5    4    4    4    4    ...          3   
2          3    3    3    3    3    3    3    2    3    3    ...          3   
3          3    3    3    3    3    3    3    3    2    2    ...          2   
4          3    3    3    2    3    3    3    2    3    3    ...          2   
5          3    3    3    3    3    4    3    2    2    2    ...          2   

userId   137037  137202  137277  137343  137686  137885  138208  138325  \
movieId                                                                   
1             4       4       4       4       4       4       3       4   
2             3       3       2       3       3       3       3       3   
3             2       3       3       3       3       2       2       3   
4             3       2       2       2       2       3       3       3   
5             2       3       2       3       3       3       2       2   

userId       name  
movieId            
1        kjhwkjhe  
2        kjhwkjhe  
3        kjhwkjhe  
4        kjhwkjhe  
5        kjhwkjhe  

[5 rows x 1001 columns]

In [0]:

for i in result_frame.index:
  if i in mm.movieId.values:
    lt.append(mm[mm['movieId'] == i].iloc[0][1])

In [0]:
pp['name']= lt

In [0]:
pp.head()

userId   156  208  359  572  586  741  768  775  903  982  \
movieId                                                     
1          4    4    4    4    4    5    4    4    4    4   
2          3    3    3    3    3    3    3    2    3    3   
3          3    3    3    3    3    3    3    3    2    2   
4          3    3    3    2    3    3    3    2    3    3   
5          3    3    3    3    3    4    3    2    2    2   

userId                  ...                  136989  137037  137202  137277  \
movieId                 ...                                                   
1                       ...                       3       4       4       4   
2                       ...                       3       3       3       2   
3                       ...                       2       2       3       3   
4                       ...                       2       3       2       2   
5                       ...                       2       2       3       2   

userId   137343  137686  137885  138208  138325  \
movieId                                           
1             4       4       4       3       4   
2             3       3       3       3       3   
3             3       3       2       2       3   
4             2       2       3       3       3   
5             3       3       3       2       2   

userId                                 name  
movieId                                      
1                          Toy Story (1995)  
2                            Jumanji (1995)  
3                   Grumpier Old Men (1995)  
4                  Waiting to Exhale (1995)  
5        Father of the Bride Part II (1995)  

[5 rows x 1001 columns]

In [0]:
rr = pp[[156,'name']]

In [0]:
pd.Series(did_rate[:,0])

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
5       1.0
6       1.0
7       1.0
8       1.0
9       1.0
10      1.0
11      0.0
12      1.0
13      1.0
14      1.0
15      1.0
16      0.0
17      1.0
18      1.0
19      1.0
20      1.0
21      1.0
22      1.0
23      0.0
24      0.0
25      0.0
26      0.0
27      1.0
28      1.0
29      1.0
       ... 
1670    0.0
1671    0.0
1672    0.0
1673    0.0
1674    0.0
1675    0.0
1676    0.0
1677    0.0
1678    0.0
1679    0.0
1680    0.0
1681    0.0
1682    0.0
1683    0.0
1684    0.0
1685    0.0
1686    0.0
1687    0.0
1688    0.0
1689    0.0
1690    0.0
1691    0.0
1692    0.0
1693    0.0
1694    0.0
1695    0.0
1696    0.0
1697    0.0
1698    0.0
1699    0.0
Length: 1700, dtype: float64

In [0]:
len(rr[156]*pd.Series(did_rate[:,0]))

2732

In [0]:
rr

userId   156                                               name
movieId                                                        
1          4                                   Toy Story (1995)
2          3                                     Jumanji (1995)
3          3                            Grumpier Old Men (1995)
4          3                           Waiting to Exhale (1995)
5          3                 Father of the Bride Part II (1995)
6          4                                        Heat (1995)
7          4                                     Sabrina (1995)
9          2                                Sudden Death (1995)
10         3                                   GoldenEye (1995)
11         4                     American President, The (1995)
12         2                 Dracula: Dead and Loving It (1995)
14         4                                       Nixon (1995)
15         3                            Cutthroat Island (1995)
16         4                                      Casino (1995)
17         5                       Sense and Sensibility (1995)
18         4                                  Four Rooms (1995)
19         3              Ace Ventura: When Nature Calls (1995)
20         3                                 Money Train (1995)
21         4                                  Get Shorty (1995)
22         3                                     Copycat (1995)
23         3                                   Assassins (1995)
24         3                                      Powder (1995)
25         4                           Leaving Las Vegas (1995)
26         3                                     Othello (1995)
28         4                                  Persuasion (1995)
29         3  City of Lost Children, The (Cité des enfants p...
31         3                             Dangerous Minds (1995)
32         5          Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
34         4                                        Babe (1995)
36         4                            Dead Man Walking (1995)
...      ...                                                ...
72011      4                               Up in the Air (2009)
72226      5                           Fantastic Mr. Fox (2009)
72998      4                                      Avatar (2009)
73017      4                             Sherlock Holmes (2009)
74458      4                              Shutter Island (2010)
74789      3                         Alice in Wonderland (2010)
76093      4                    How to Train Your Dragon (2010)
76251      4                                    Kick-Ass (2010)
77561      4                                  Iron Man 2 (2010)
78499      5                                 Toy Story 3 (2010)
79091      4                               Despicable Me (2010)
79132      4                                   Inception (2010)
79702      5                 Scott Pilgrim vs. the World (2010)
80463      5                         Social Network, The (2010)
81591      4                                  Black Swan (2010)
81834      4  Harry Potter and the Deathly Hallows: Part 1 (...
81845      4                          King's Speech, The (2010)
82459      4                                   True Grit (2010)
85414      3                                 Source Code (2011)
87232      4                          X-Men: First Class (2011)
88125      4  Harry Potter and the Deathly Hallows: Part 2 (...
88129      4                                       Drive (2011)
89745      4                               Avengers, The (2012)
91500      3                           Hunger Games, The (2012)
91529      5                      Dark Knight Rises, The (2012)
92259      4                                Intouchables (2011)
96079      5                                     Skyfall (2012)
96610      4                                      Looper (2012)
98809      4          Hobbit: An Unexpected Journey, The (2012)
99114      4                    

In [0]:
dd = result_frame[[156]]

In [0]:
dd.index

Int64Index([    1,     2,     3,     4,     5,     6,     7,     9,    10,
               11,
            ...
            88125, 88129, 89745, 91500, 91529, 92259, 96079, 96610, 98809,
            99114],
           dtype='int64', name='movieId', length=1700)

In [0]:
85414 in movie.movieId

False

In [0]:
for i in dd.index:
  if i in movie.movieId:
    print(i)

1
2
3
4
5
6
7
9
10
11
12
14
15
16
17
18
19
20
21
22
23
24
25
26
28
29
31
32
34
36
39
41
44
45
46
47
48
50
52
58
60
62
65
69
70
73
74
76
79
81
85
86
88
89
94
95
100
101
104
105
107
110
111
112
122
125
135
140
141
144
145
147
150
151
153
154
158
160
161
162
163
164
165
168
169
170
172
173
175
180
181
185
186
193
194
195
196
198
203
204
207
208
215
216
218
222
223
224
225
227
230
231
232
233
234
235
236
237
239
246
247
248
249
252
253
256
257
260
261
262
265
266
267
272
273
276
277
280
281
282
288
289
290
292
293
296
300
303
305
306
307
308
314
315
316
317
318
319
322
327
329
333
337
338
339
342
344
345
348
349
350
351
353
355
356
357
361
362
364
367
368
370
371
372
373
374
376
377
379
380
381
382
383
405
410
412
413
415
417
419
420
426
427
428
431
432
434
435
440
441
442
446
448
450
454
455
457
464
466
468
471
474
475
477
480
481
482
485
489
490
491
492
493
494
497
500
502
507
508
509
514
515
516
517
519
520
524
527
529
531
532
533
534
535
537
538
539
540
541
542
543
546
548
550
551
552


In [0]:
print(j)

1528


In [0]:
movie

movieId                                              title  \
0            1                                   Toy Story (1995)   
1            2                                     Jumanji (1995)   
2            3                            Grumpier Old Men (1995)   
3            4                           Waiting to Exhale (1995)   
4            5                 Father of the Bride Part II (1995)   
5            6                                        Heat (1995)   
6            7                                     Sabrina (1995)   
7            8                                Tom and Huck (1995)   
8            9                                Sudden Death (1995)   
9           10                                   GoldenEye (1995)   
10          11                     American President, The (1995)   
11          12                 Dracula: Dead and Loving It (1995)   
12          13                                       Balto (1995)   
13          14                                       Nixon (1995)   
14          15                            Cutthroat Island (1995)   
15          16                                      Casino (1995)   
16          17                       Sense and Sensibility (1995)   
17          18                                  Four Rooms (1995)   
18          19              Ace Ventura: When Nature Calls (1995)   
19          20                                 Money Train (1995)   
20          21                                  Get Shorty (1995)   
21          22                                     Copycat (1995)   
22          23                                   Assassins (1995)   
23          24                                      Powder (1995)   
24          25                           Leaving Las Vegas (1995)   
25          26                                     Othello (1995)   
26          27                                Now and Then (1995)   
27          28                                  Persuasion (1995)   
28          29  City of Lost Children, The (Cité des enfants p...   
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...        ...                                                ...   
27248   131146                      Werner - Volles Rooäää (1999)   
27249   131148                                  What A Man (2011)   
27250   131150         7 Dwarves: The Forest Is Not Enough (2006)   
27251   131152                                 The Fat Spy (1966)   
27252   131154  Die Bademeister – Weiber, saufen, Leben retten...   
27253   131156                         Ants in the Pants 2 (2002)   
27254   131158                                Manta, Manta (1991)   
27255   131160                  Oscar and the Lady in Pink (2009)   
27256   131162                      Por un puñado de besos (2014)   
27257   131164                               Vietnam in HD (2011)   
27258   131166                                  WWII IN HD (2009)   
27259   131168                                     Phoenix (2014)   
27260   131170                                   Parallels (2015)   
27261   131172                              Closed Curtain (2013)   
27262   131174                                   Gentlemen (2014)   
27263   131176                             A Second Chance (2014)   
27264   131180                     Dead Rising: Watchtower (2015)   
27265   131231                                     Standby (2014)   
27266   131237                         What Men Talk About (2010)   
27267   131239                          Three Quarter Moon (2011)   
27268   131241                           Ants in the Pants (2000)   
27269   131243                Werner - Gekotzt wird später (2003)   
27270   131248                              Brother Bear 2 (2006)   
27271   131250                              No More School (2000)   
27272   131252  Forklift Driver Klaus: The First Day on the Jo...   
27273   131254                       Kein Bund für's Leben (2007)   
27274