<a href="https://colab.research.google.com/github/rishikesh1410/Projects/blob/master/RecommenderSystemPyTorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
from __future__ import print_function, division

# Torch Libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

# Libraries
import numpy as np
import time
import os
import copy
import cv2
import pandas as pd
import matplotlib.pyplot as plt
from numpy import *
from scipy import optimize
np.random.seed(1)

In [0]:
os.chdir("/gdrive/My Drive/data/movielens")

In [0]:
movie = pd.read_csv('movie.csv')
rating = pd.read_csv('rating.csv')
rating_with_name = pd.read_csv('rating_with_name.csv')

In [0]:
user_prefs = pd.read_csv('new_user_prefs.csv')
movie_features = pd.read_csv('new_movie_features.csv')

In [0]:
movie_features = movie_features.iloc[:,1:]
user_prefs = user_prefs.iloc[:,1:]

In [7]:
movie_features

0         1         2
0     0.969737 -0.504606 -0.759909
1     0.157291 -0.405990 -0.527766
2     0.440388 -1.066609  0.059473
3     0.820170 -1.179844  0.111779
4     1.018596 -1.267757  0.503781
5     0.540590 -0.343280  0.246707
6    -0.008349 -0.525246 -0.230984
7     0.319073 -1.218923 -0.746284
8     0.652205 -0.697770  0.198391
9     0.431078 -1.042976 -0.454492
10    0.438273 -0.605619 -0.330852
11   -0.341447 -0.130297 -0.075634
12    0.423943 -1.159905  0.192340
13    0.646676 -0.355029 -0.005871
14    0.849307 -0.912137  0.570745
15    0.082348 -0.143945 -0.204888
16    0.275691 -0.632102 -0.582021
17    0.279971 -1.041157  0.581961
18    0.323242  0.233830 -0.880527
19    0.671229 -0.702249 -0.450895
20    0.602762 -1.138175  0.204921
21    0.180376 -0.351172 -0.352892
22    0.438017 -0.298975 -0.832514
23    0.238183 -0.271464 -0.310074
24    0.566087 -0.228215 -0.309442
25    0.625204 -0.775580 -0.029139
26   -0.305488 -0.628831 -0.916349
27   -0.299103 -0.689078  0.763326
28    0.993581 -0.630480  0.098373
29   -0.447084  0.315113 -0.816616
...        ...       ...       ...
1670  0.740668 -0.245455 -0.309544
1671  0.565724 -0.738749  0.731815
1672  0.404443 -0.605376  0.067319
1673  0.287236 -0.998410  0.153755
1674  0.074416 -0.136575 -0.291397
1675  0.101620 -0.569094 -0.279489
1676  0.525741 -0.750346  0.315580
1677  0.265272 -0.697316 -0.117855
1678  0.138350 -0.596802 -0.777907
1679  0.482471 -0.421239 -1.026854
1680 -0.371449 -0.739321 -0.034148
1681  0.162608 -0.392770  0.126382
1682  0.753627 -0.418130  0.046530
1683  0.359906 -0.437998 -0.220309
1684  0.631824 -0.617858  0.300962
1685  0.206900  0.245900  0.282881
1686  0.679274 -0.327336 -0.613945
1687  0.395810 -0.260619 -0.260726
1688  0.283449 -0.158072 -0.100182
1689  0.843102 -0.250646 -0.223842
1690  0.463079 -0.412978 -0.488727
1691 -0.085857 -0.180948 -0.082489
1692  0.784265 -0.980321 -0.913596
1693  0.546200 -0.206341 -0.768163
1694  0.559333 -0.501187 -1.009766
1695 -0.183145 -0.747880 -0.039608
1696  0.635974  0.568395 -0.570366
1697  0.390363 -0.427450  0.478298
1698  0.773600 -0.404437 -0.095447
1699  0.747281 -0.238105 -0.226148

[1700 rows x 3 columns]

In [8]:
user_prefs

0         1         2
0    0.100705 -0.912991 -0.359637
1   -0.465897 -0.258130 -0.088400
2    0.337208  0.086550  0.549299
3   -0.655845 -1.108610 -0.649265
4   -0.372976 -0.600798 -0.030201
5    0.033659 -0.745804 -0.497728
6   -0.156978 -0.350801 -0.328748
7   -0.316445  0.118591 -0.440361
8    0.306367 -0.076792  0.137638
9    0.510554  0.459274  0.385452
10  -0.646327 -0.122602  0.008192
11  -0.537064 -0.555462 -0.325963
12  -0.290427 -0.517258 -0.087430
13   0.905410  0.069010  0.792682
14  -0.409971  1.039136  0.383553
15   0.373411 -0.429840  0.123165
16  -0.491688 -0.136222  0.110460
17  -0.635709 -0.979889 -0.479224
18  -0.364147 -0.484046  0.386501
19   0.994950  0.052636  0.741756
20  -0.119588 -0.473691  0.011570
21  -0.202057 -0.218881  0.584853
22   0.659081  0.089196 -0.840714
23  -0.528599  0.818716  0.225819
24  -0.438195  0.059906 -0.003182
25   0.003479 -0.352909  0.370660
26   0.055506 -0.149901 -0.095179
27  -0.304501 -0.403579 -0.702322
28   0.643405  0.853861 -0.596889
29  -0.875584  0.100688 -0.654388
..        ...       ...       ...
970 -0.454492 -0.182799  0.066506
971 -0.036168 -0.211803  0.097999
972 -0.328645  0.074843  0.271843
973  0.409760  0.277267 -0.040826
974 -0.291425  1.098882  0.556513
975  0.783062 -0.552597 -0.621065
976  1.002136  0.246214  0.176400
977  0.047907  0.793558  0.811961
978 -0.124553 -0.434730 -0.665903
979 -0.213167 -0.167371  0.703967
980  0.152154  0.347226 -0.681762
981 -0.274295 -0.104433 -0.203341
982 -0.388084  0.597662 -0.413083
983  0.488029 -0.084802 -0.552092
984 -0.499266  0.510354  0.435989
985 -0.271274  0.415295 -0.416524
986 -0.606728 -0.344937  0.010794
987 -0.190651  0.110675  0.240415
988 -0.373395 -0.625794 -0.228720
989 -1.456154 -1.058051 -0.285957
990  0.117263 -0.570362 -0.110660
991 -1.102909  0.917009  0.286867
992 -0.437077 -0.394460  0.333628
993  0.092756 -0.507954 -0.816989
994 -0.306911 -0.904126 -0.337860
995  0.615389  0.585731 -0.266556
996  0.641141 -0.018013 -0.765020
997  0.397211  0.652008  0.562818
998 -0.083866  0.833050  0.280018
999  0.573845 -0.277843 -0.023501

[1000 rows x 3 columns]

In [0]:
movie_features = np.array(movie_features)
user_prefs = np.array(user_prefs)

In [0]:
def loss(movie_features, user_prefs, ratings, did_rate):

  cost = torch.sum( ((torch.mm(movie_features, torch.t(user_prefs)) * did_rate) - ratings) ** 2 ) / (1700*1000)
  return cost

In [0]:
def tabular_preview(ratings, n=15):
  
    user_groups = ratings.groupby('userId')['rating'].count()
    top_users = user_groups.sort_values(ascending=False)[:1000]

    movie_groups = ratings.groupby('movieId')['rating'].count()
    top_movies = movie_groups.sort_values(ascending=False)[:1700]

    top = (
        ratings.
        join(top_movies, rsuffix='_r', how='inner', on='movieId').
        join(top_users, rsuffix='_r', how='inner', on='userId'))

    return pd.crosstab(top.movieId, top.userId, top.rating, aggfunc=np.sum)

In [0]:
frame = tabular_preview(rating)

In [0]:
train_data = np.array(frame)

In [0]:
did_rate = np.ndarray(shape = (1700,1000))

In [0]:
for i in range(1700):
  for j in range(1000):
    if np.isnan(train_data[i][j]):
      train_data[i][j]=0

In [0]:
did_rate = (train_data != 0 )* 1

In [0]:
def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]

    ratings_mean = np.zeros(shape = (num_movies, 1))
    ratings_norm = np.zeros(shape = ratings.shape)

    for i in range(num_movies): 
        idx = np.where(did_rate[i] == True)[0]
        ratings_mean[i] = np.mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]

    return ratings_norm, ratings_mean

In [0]:
rating, rating_mean = normalize_ratings(train_data, did_rate)

In [0]:
movie_features = torch.tensor(movie_features, requires_grad=True)
user_prefs = torch.tensor(user_prefs, requires_grad=True)
did_rate = torch.tensor(did_rate, dtype=torch.double, requires_grad=False)
rating = torch.tensor(rating, requires_grad=False)
rating_mean = torch.tensor(rating_mean, dtype=torch.double, requires_grad=False)

In [20]:
loss(movie_features, user_prefs, rating, did_rate)

tensor(0.3944, dtype=torch.float64, grad_fn=<DivBackward0>)

# **PREDICTIONS AND SAVING THE FILE**

In [0]:
predictions = torch.mm(movie_features, torch.t(user_prefs))

In [0]:
predictions = predictions + rating_mean

In [25]:
all_predictions = torch.tensor(predictions+0.5 , dtype=torch.long)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [26]:
print(all_predictions)

tensor([[5, 4, 4,  ..., 4, 3, 5],
        [3, 3, 3,  ..., 2, 2, 3],
        [4, 3, 3,  ..., 2, 2, 3],
        ...,
        [4, 4, 4,  ..., 4, 3, 4],
        [4, 3, 4,  ..., 4, 3, 4],
        [4, 4, 4,  ..., 4, 4, 4]])


In [0]:
all_predictions_arr = all_predictions.numpy()

In [0]:
result_frame = pd.DataFrame(all_predictions_arr, index=frame.index, columns = frame.columns)

In [29]:
result_frame

userId   156     208     359     572     586     741     768     775     \
movieId                                                                   
1             5       4       4       4       4       5       4       4   
2             3       3       3       4       3       3       3       3   
3             4       3       3       4       3       4       3       2   
4             4       2       3       3       3       3       3       2   
5             4       2       3       3       3       3       3       2   
6             4       4       4       4       4       4       4       3   
7             4       3       3       4       3       3       3       3   
9             4       3       2       4       3       4       3       2   
10            4       3       4       3       3       4       3       3   
11            5       3       3       5       4       4       4       3   
12            3       2       2       3       2       3       2       2   
14            4       4       3       4       4       4       4       4   
15            3       2       2       3       3       3       3       2   
16            4       4       4       4       4       4       4       3   
17            4       4       4       4       4       4       4       3   
18            3       3       3       3       3       3       3       3   
19            3       2       2       3       3       3       3       2   
20            3       2       3       3       3       3       3       2   
21            4       3       3       4       3       4       4       4   
22            4       3       3       4       3       4       3       3   
23            4       3       3       3       3       3       3       2   
24            3       3       3       3       3       3       3       3   
25            4       4       3       4       4       4       4       4   
26            4       3       3       4       3       4       3       3   
28            4       4       4       4       4       4       4       4   
29            5       4       4       4       4       4       4       4   
31            4       3       2       4       3       4       3       3   
32            4       4       4       4       4       4       4       4   
34            4       3       4       4       4       4       4       3   
36            4       4       3       4       4       4       4       4   
...         ...     ...     ...     ...     ...     ...     ...     ...   
72011         4       4       4       4       4       4       4       4   
72226         4       4       4       4       4       4       4       3   
72998         4       4       4       4       4       4       4       3   
73017         4       4       4       4       4       4       4       3   
74458         4       4       3       4       4       4       4       4   
74789         4       3       3       4       3       4       3       3   
76093         4       4       4       4       4       4       4       3   
76251         4       4       4       4       4       4       4       3   
77561         4       3       3       4       4       4       4       4   
78499         5       4       4       5       4       5       4       4   
79091         4       4       3       5       4       4       4       3   
79132         4       4       4       4       4       4       4       4   
79702         4       3       4       4       4       4       4       3   
80463         4       4       4       4       4       4       4       4   
81591         4       4       4       4       4       4       4       3   
81834         3       3       4       3       3       3       3       3   
81845         5       4       4       4       4       4       4       4   
82459         4       4       4       4       4       4       4       4   
85414         4       4       4       4       4       4       4       4   
87232         4       3       4       3       3       4       4       3   
88125         4       4  

In [0]:
result_frame.to_csv('result_frame.csv')

# **ADD NEW RATINGS**

In [0]:
movie_features = movie_features.detach().numpy()
user_prefs = user_prefs.detach().numpy()

In [0]:
my_rating = np.zeros(shape=(1700,1))
my_did_rate = np.zeros(shape=(1700,1))

In [0]:
# lt=[]
# pp = frame.copy()
# pp['name']="abcd"
# pp.head()
# for i in frame.index:
#   if i in movie.movieId.values:
#     lt.append(movie[movie['movieId'] == i].iloc[0][1])
# pp['name']= lt
# pp.to_csv('rating_with_name.csv')

In [34]:
rating_with_name.head()

movieId  156  208  359  572  586  741  768  775  903  \
0        1  5.0  4.0  5.0  5.0  2.5  5.0  NaN  4.5  4.0   
1        2  5.0  NaN  NaN  3.5  3.0  3.0  3.0  2.0  4.0   
2        3  2.0  NaN  NaN  3.5  2.0  3.0  NaN  3.5  2.0   
3        4  3.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  2.0   
4        5  3.0  NaN  NaN  3.5  3.0  4.0  2.0  1.0  3.0   

                  ...                  136989  137037  137202  137277  137343  \
0                 ...                     2.0     4.0     4.5     4.0     4.0   
1                 ...                     2.0     3.0     2.5     2.5     2.5   
2                 ...                     NaN     2.0     3.5     3.0     3.5   
3                 ...                     NaN     NaN     NaN     NaN     NaN   
4                 ...                     4.5     3.0     NaN     3.0     3.5   

   137686  137885  138208  138325                                name  
0     5.0     5.0     3.0     5.0                    Toy Story (1995)  
1     3.0     3.0     2.0     3.0                      Jumanji (1995)  
2     3.0     4.0     2.0     NaN             Grumpier Old Men (1995)  
3     NaN     2.0     2.0     NaN            Waiting to Exhale (1995)  
4     NaN     3.0     2.0     NaN  Father of the Bride Part II (1995)  

[5 rows x 1002 columns]

In [0]:
for i in range(100):
  my_rating[i]=5
  my_did_rate[i]=1

In [36]:
rating_with_name[rating_with_name['movieId']==81834]

movieId  156  208  359  572  586  741  768  775  903  \
1685    81834  NaN  NaN  NaN  NaN  NaN  NaN  3.5  NaN  NaN   

                            ...                          136989  137037  \
1685                        ...                             NaN     NaN   

      137202  137277  137343  137686  137885  138208  138325  \
1685     NaN     3.0     NaN     NaN     NaN     4.0     NaN   

                                                   name  
1685  Harry Potter and the Deathly Hallows: Part 1 (...  

[1 rows x 1002 columns]

In [0]:
did_rate = np.append(did_rate, my_did_rate, axis=1)

In [0]:
train_data = np.append(train_data, my_rating, axis=1)

In [39]:
train_data.shape

(1700, 1001)

In [40]:
did_rate.shape

(1700, 1001)

In [0]:
my_prefs = np.random.randn(1,3)

In [0]:
user_prefs = np.append(user_prefs, my_prefs, axis=0)

In [43]:
user_prefs.shape

(1001, 3)

In [44]:
movie_features.shape

(1700, 3)

In [45]:
rating.shape

torch.Size([1700, 1000])

In [0]:
rating, rating_mean = normalize_ratings(train_data, did_rate)

In [48]:
rating.shape

(1700, 1001)

In [49]:
movie_features

array([[ 0.96973653, -0.50460597, -0.75990939],
       [ 0.15729144, -0.40599005, -0.52776559],
       [ 0.44038786, -1.06660895,  0.059473  ],
       ...,
       [ 0.39036299, -0.42745025,  0.47829839],
       [ 0.77360034, -0.40443659, -0.09544745],
       [ 0.74728106, -0.2381054 , -0.22614752]])

In [50]:
my_prefs

array([[ 1.62434536, -0.61175641, -0.52817175]])

In [0]:
movie_features = torch.tensor(movie_features, requires_grad=True)
user_prefs = torch.tensor(user_prefs, requires_grad=True)
did_rate = torch.tensor(did_rate, dtype=torch.double, requires_grad=False)
rating = torch.tensor(rating, requires_grad=False)
rating_mean = torch.tensor(rating_mean, dtype=torch.double, requires_grad=False)

In [52]:
loss(movie_features, user_prefs, rating, did_rate)

tensor(0.3945, dtype=torch.float64, grad_fn=<DivBackward0>)

In [53]:
did_rate

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 0., 0.,  ..., 1., 1., 1.],
        [1., 0., 0.,  ..., 1., 0., 1.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)